package com.example.inventory.shared;

public enum ApiErrorCode {
    INVALID_REQUEST,
    VALIDATION_FAILED,
    RESOURCE_NOT_FOUND,
    CONFLICT,
    DATA_INTEGRITY_VIOLATION,
    AUTHENTICATION_FAILED,
    AUTHENTICATION_REQUIRED,
    ACCESS_DENIED,
    METHOD_NOT_ALLOWED,
    UNSUPPORTED_MEDIA_TYPE,
    INTERNAL_ERROR
}
